### ISSUE TITLE
Change the load() function to open file in a 'with' statement 

### ISSUE THREAD

**Issue by mthorntonhanks** [mthorntonhanks/lite_wave#3]

**Comment by devbazregari** [comment]
@mthorntonhanks 
hi. I hope you're doing great. in which file the load function is ?
actually, do you want to open the file with this statement "with" instead of open()

**Comment by mthorntonhanks** [comment]
Hi I'm good hope you too. I think load() is in lite_wave.py. Thanks


________________________________
